"""ScriptGuard AI — Streamlit interface: upload one or more PDF scripts and generate
individual coverage + slate prioritization, with real parallel market research and
agent self-QA."""

import os
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

from scriptguard.pdf_utils import extract_text_from_pdf
from scriptguard.pipeline import RateLimitExceeded, run_slate_triage
from scriptguard.schemas import CoverageReport

load_dotenv()

st.set_page_config(page_title="ScriptGuard AI", layout="wide")

st.title("ScriptGuard AI")
st.caption(
    "Script coverage generated by a committee of persona agents that debates over 2 "
    "rounds, with real parallel market research, self-QA critique, and slate prioritization."
)

if not os.getenv("GOOGLE_API_KEY"):
    st.warning("Missing GOOGLE_API_KEY in the .env file")
if not os.getenv("PARALLEL_API_KEY"):
    st.warning("Missing PARALLEL_API_KEY in the .env file")

st.session_state.setdefault("processing", False)
st.session_state.setdefault("results", None)
st.session_state.setdefault("run_source", None)

st.markdown("### How it works — 17 agents orchestrated with Google ADK")
stage1, stage2, stage3, stage4 = st.columns(4)
with stage1:
    with st.container(border=True, height=230):
        st.markdown("**1. Narrative analysis**")
        st.caption("1 agent")
        st.write(
            "Gemini analyzes the full script: three-act structure, characters, "
            "genre, tone, and pacing."
        )
with stage2:
    with st.container(border=True, height=230):
        st.markdown("**2. Market research**")
        st.caption("3 agents — 2 in parallel + 1 formatter")
        st.write(
            "2 agents in parallel (`ParallelAgent`) research box-office "
            "comparables and genre trends via Parallel's Search API; a third "
            "converts those notes into structured JSON."
        )
with stage3:
    with st.container(border=True, height=230):
        st.markdown("**3. Greenlight Committee**")
        st.caption("9 agents — 4 personas × 2 rounds + 1 moderator")
        st.write(
            "4 persona agents (Creative Producer, Intl. Distribution, Financial "
            "Analyst, Indie/Festival Reader) give their opinion and then debate "
            "in a second round, reacting to each other; a moderator synthesizes "
            "the final verdict."
        )
with stage4:
    with st.container(border=True, height=230):
        st.markdown("**4. QA + Prioritization**")
        st.caption("4 agents — 3 in the QA loop + 1 for prioritization")
        st.write(
            "A 3-agent `LoopAgent` audits the report against the real research "
            "(up to 3 iterations) and, if you upload several scripts, an "
            "additional agent prioritizes the whole slate as a portfolio."
        )
st.caption(
    "Orchestrated with Google ADK (`SequentialAgent` + `ParallelAgent` x3 + "
    "`LoopAgent`) on top of Gemini, with real Parallel research on every run."
)
st.divider()


def esc(text: str) -> str:
    """Escapes '$' so Streamlit doesn't interpret it as LaTeX when rendering agent-generated text."""
    return text.replace("$", r"\$")


VERDICT_COLOR = {"RECOMMEND": "green", "CONSIDER": "orange", "PASS": "red"}
CONFIDENCE_COLOR = {"HIGH": "green", "MEDIUM": "orange", "LOW": "red"}


def render_report_detail(report: CoverageReport) -> None:
    verdict_color = VERDICT_COLOR[report.verdict]
    confidence_color = CONFIDENCE_COLOR[report.confidence]
    st.header(f":{verdict_color}[{report.verdict}]  ·  confidence :{confidence_color}[{report.confidence}]")
    st.subheader(esc(report.script_analysis.title))
    st.write(esc(report.summary))

    if report.unsupported_claims:
        st.warning(
            "The QA agent flagged claims not sufficiently backed by the research "
            "(already corrected in this report, shown here for audit reference):\n\n"
            + "\n".join(f"- {esc(c)}" for c in report.unsupported_claims)
        )
    st.caption(f"QA note: {esc(report.qa_notes)}")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Strengths**")
        for item in report.strengths:
            st.markdown(f"- {esc(item)}")
    with col2:
        st.markdown("**Weaknesses**")
        for item in report.weaknesses:
            st.markdown(f"- {esc(item)}")

    st.markdown("### Market positioning")
    st.write(esc(report.market_positioning))

    st.markdown("### Verdict justification")
    st.write(esc(report.justification))
    if report.dissenting_personas:
        st.info(
            "The committee did NOT reach unanimous consensus. Dissenting from the final verdict: "
            + ", ".join(esc(p) for p in report.dissenting_personas)
        )

    with st.expander("Greenlight Committee Debate (2 rounds)", expanded=False):
        opinions_by_persona_r1 = {op.persona: op for op in report.committee_round1}
        for op2 in report.committee_round2:
            op1 = opinions_by_persona_r1.get(op2.persona)
            changed = op1 is not None and op1.verdict_lean != op2.verdict_lean
            st.markdown(f"**{esc(op2.persona)}**")
            if op1 is not None:
                st.markdown(f"- *Round 1:* `{op1.verdict_lean}` — {esc(op1.argument)}")
            change_flag = " _(changed position)_" if changed else ""
            st.markdown(f"- *Round 2 (debate):* `{op2.verdict_lean}`{change_flag} — {esc(op2.argument)}")
            st.markdown(f"  - _Concern:_ {esc(op2.concern)}")
            st.markdown("")

    with st.expander("Full narrative analysis"):
        sa = report.script_analysis
        st.markdown(f"**Logline:** {esc(sa.logline)}")
        st.markdown(f"**Genre:** {esc(sa.genre)}  |  **Tone:** {esc(sa.tone)}")
        st.markdown("**Three-act structure**")
        for act in sa.three_act_structure:
            st.markdown(f"- *Act {act.act_number} — {esc(act.title)}:* {esc(act.summary)}")
        st.markdown("**Main characters**")
        for char in sa.main_characters:
            st.markdown(f"- **{esc(char.name)}**: {esc(char.description)} _(arc: {esc(char.arc)})_")
        st.markdown(f"**Pacing:** {esc(sa.pacing_notes)}")

    with st.expander("Full market research"):
        mr = report.market_research
        st.markdown("**Comparable films**")
        for title in mr.comparable_titles:
            st.markdown(
                f"- **{esc(title.title)} ({esc(title.year)})**: {esc(title.box_office_or_reception)} "
                f"— _{esc(title.similarity_notes)}_"
            )
        st.markdown(f"**Genre trends:** {esc(mr.genre_trends)}")
        st.markdown("**Market insights**")
        for insight in mr.market_insights:
            st.markdown(f"- {esc(insight)}")
        if mr.sources:
            st.markdown("**Sources**")
            for source in mr.sources:
                st.markdown(f"- {source}")


MAX_SCRIPTS = 3
SAMPLE_SCRIPT_PATH = Path(__file__).parent / "sample_scripts" / "cold_storage_sample.pdf"


@st.cache_data
def _load_sample_pdf_bytes() -> bytes:
    return SAMPLE_SCRIPT_PATH.read_bytes()


uploaded_files = st.file_uploader(
    f"Upload one or more PDF scripts (max {MAX_SCRIPTS} per run)",
    type=["pdf"],
    accept_multiple_files=True,
)

if uploaded_files and len(uploaded_files) > MAX_SCRIPTS:
    st.error(
        f"You uploaded {len(uploaded_files)} PDFs, the max per run is {MAX_SCRIPTS}. "
        "Remove some and try again."
    )
    uploaded_files = None

def _start_processing(source: str) -> None:
    st.session_state.processing = True
    st.session_state.results = None
    st.session_state.run_source = source


col_generate, col_sample = st.columns(2)
with col_generate:
    st.button(
        "Generate slate coverage",
        type="primary",
        disabled=st.session_state.processing or not uploaded_files,
        on_click=_start_processing,
        args=("upload",),
    )
with col_sample:
    st.download_button(
        "View / download the bundled sample script (Cold Storage.pdf)",
        data=_load_sample_pdf_bytes(),
        file_name="cold_storage_sample.pdf",
        mime="application/pdf",
    )
    st.button(
        "Try with a sample script",
        disabled=st.session_state.processing,
        on_click=_start_processing,
        args=("sample",),
    )

if st.session_state.processing:
    if st.session_state.run_source == "sample":
        script_texts = [extract_text_from_pdf(_load_sample_pdf_bytes())]
    else:
        script_texts = []
        with st.spinner(f"Extracting text from {len(uploaded_files)} PDF(s)..."):
            for f in uploaded_files:
                text = extract_text_from_pdf(f.read())
                if text:
                    script_texts.append(text)
                else:
                    st.warning(f"Couldn't extract text from {f.name} (scanned PDF?), skipping it.")

    if not script_texts:
        st.error("No PDF produced readable text.")
        st.session_state.processing = False
    else:
        status_msg = (
            f"Analyzing {len(script_texts)} script(s), researching the market in parallel, "
            "auditing quality, and prioritizing the slate... this can take a few minutes."
        )
        with st.spinner(status_msg):
            try:
                reports, ranking = run_slate_triage(script_texts)
            except RateLimitExceeded as exc:
                st.session_state.processing = False
                st.warning(str(exc))
                st.stop()
            except Exception as exc:  # noqa: BLE001 — surface any pipeline failure to the user
                st.session_state.processing = False
                st.error(f"Error generating coverage: {exc}")
                st.stop()

        st.session_state.results = (reports, ranking)
        st.session_state.processing = False

if st.session_state.results is not None:
    reports, ranking = st.session_state.results
    reports_by_title = {r.script_analysis.title: r for r in reports}

    st.header("Slate prioritization")
    for entry in ranking.ranked_slate:
        verdict_color = VERDICT_COLOR[entry.verdict]
        confidence_color = CONFIDENCE_COLOR[entry.confidence]
        st.markdown(
            f"**#{entry.rank} — {esc(entry.title)}** "
            f":{verdict_color}[{entry.verdict}] · confidence :{confidence_color}[{entry.confidence}] "
            f"— {esc(entry.one_line_rationale)}"
        )

    st.markdown("**Portfolio observations**")
    for insight in ranking.portfolio_insights:
        st.markdown(f"- {esc(insight)}")

    st.markdown("**Executive recommendation**")
    st.write(esc(ranking.overall_recommendation))

    st.divider()
    st.header("Individual coverage per script")
    for entry in ranking.ranked_slate:
        report = reports_by_title.get(entry.title)
        if report is None:
            continue
        st.markdown(f"## #{entry.rank} — {esc(report.script_analysis.title)}")
        render_report_detail(report)
        st.divider()
